### ISSUE TITLE
VideoINSTA: Zero-shot Long Video Understanding via Informative Spatial-Temporal Reasoning with LLMs

### ISSUE THREAD

**Issue by mayhugotong** [ttengwang/Awesome_Long_Form_Video_Understanding#11]
Dear Authors,

I would like to share my paper in EMNLP2024 "VideoINSTA: Zero-shot Long Video Understanding via Informative Spatial-Temporal Reasoning with LLMs". (https://www.arxiv.org/abs/2409.20365)
It would be greatly appreciated if you could please add it to the repository.

All the best wishes to your research!

**Comment by LJungang** [comment]
Thank you for your contribution to the field of long-form video understanding, and we will consider your request.
